### PR TITLE
[permissions] Whitelist user's dconf. JB#54408 OMP#JOLLA-162

### PR DESCRIPTION
**Pull request by rainemak**

### CODE REVIEW

**Comment by rainemak** [comment]
@okodron review appreciated.

**Review by okodron — APPROVED** [review]
OMP#JOLLA-162 as well?

**Comment by Tomin1** [comment]
I wonder if whitelisting a file can cause bugs with older devices as they can't delete or rename a file that's mounted to another namespace (bug in older kernels). Could we whitelist the directory instead?

**Comment by rainemak** [comment]
> I wonder if whitelisting the files can cause bugs with older devices as they can't delete or rename a file that's mounted to another namespace (bug in older kernels). Could we whitelist the directory instead?

Good idea. Adding whitelisting for the dirs + added mkdir just in case.

**Review by Tomin1 — APPROVED** [review]

**Pull request merged**
