### PR TITLE
Call recorder permissions for Phone

### PR DESCRIPTION
**Pull request by b100dian**
It seems the call recording function cannot store the audio files.
This is my attempt to give the phone app the required permissions.

Not sure if this should go into Phone.permissions or voicecall-ui though

### CODE REVIEW

**Comment by b100dian** [comment]
@abranson I know you recently modified the hosts file access permissions, can you also take a look at this?

**Comment by pvuorela** [comment]
This already in: https://github.com/sailfishos/sailjail-permissions/pull/49

**Comment by b100dian** [comment]
Thanks @pvuorela, it is not clear to me how the CallRecordings permission is linked to the voicecall-ui or Phone permissions (and if the CallRecordings folder is automatically created). Is there any other commit linking the above?
Or the question is more: how can I update the rules from this whole repo on my device, I just build the rpm and upon installing it refreshes the current 4.0.1 settings?

**Comment by pvuorela** [comment]
There was also a change in the voicecall app side for requiting the new CallRecordings permission. If you compile an rpm from this repository you can then manually edit the .desktop file for the new permission. Or atlernatively use this locally if you need it working. Will be fixed in the next release anyway.

**Comment by b100dian** [comment]
Thanks @pvuorela, I think I'll wait for the next release and go ahead with my patch for now, but am glad this has been already worked on. I think you can close this now.

**Pull request closed without merging**
