### PR TITLE
[permissions] Cleanup browser profile. Fixes JB#52736

### PR DESCRIPTION
**Pull request by rainemak**

### CODE REVIEW

**Review by okodron — APPROVED** [review]
Looks ok

**Review by Tomin1 — APPROVED** [review]
LGTM.

You should be able to remove also that `dbus-user.own org.sailfishos.browser` line if you wish.

**Comment by rainemak** [comment]
> LGTM.
> 
> You should be able to remove also that `dbus-user.own org.sailfishos.browser` line if you wish.

Added a commit on top.

**Review by okodron — APPROVED** [review]

**Review by Tomin1 — APPROVED** [review]

**Comment by rainemak** [comment]
Rebased

**Pull request merged**
