### PR TITLE
[permissions] Amend Sharing permission with new discovery API interfaces. Contributes to JB#54084 OMP#JOLLA-113

### PR DESCRIPTION
**Pull request by chriadam**

### CODE REVIEW

**Comment by chriadam** [comment]
Note: needs to be retargetted to master once jb53987-share-api branch PR is merged.

**Comment by okodron** [comment]
See also https://git.sailfishos.org/mer-core/transfer-engine/merge_requests/25

**Review by okodron — APPROVED** [review]

**Comment by LaakkonenJussi** [comment]
The task was closed as invalid so should this exist anymore then?

**Comment by chriadam** [comment]
Indeed, Pekka decided that this wasn't needed, so closing as invalid

**Pull request closed without merging**
